<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <Configurations>LatestOnly;All</Configurations>
        <Platforms>AnyCPU</Platforms>
        <IsPackable>false</IsPackable>
        <GenerateSBOM>false</GenerateSBOM>
    </PropertyGroup>

    <PropertyGroup>
      <Optimize>true</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'LatestOnly' ">
      <DefineConstants>TRACE LATEST_RUNTIME_ONLY</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\TextPress\TextPress.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    </ItemGroup>

</Project>
